force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PLants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/Species__c.field-meta.xml
<CustomField>
    <fullName>Species__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Es el campo que relaciona especie con plata</description>
    <label>Species</label>
    <referenceTo>Species__c</referenceTo>
    <relationshipLabel>PLants</relationshipLabel>
    <relationshipName>PLants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Species__c/fields/Summer_Watering_Summer__c.field-meta.xml
<CustomField>
    <fullName>Summer_Watering_Summer__c</fullName>
    <label>Summer_Watering_Summer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dalily</fullName>
            </value>
            <value>
                <fullName>Twice per week</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every other week</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Species__c/fields/Winter_Watering_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Winter_Watering_Frequency__c</fullName>
    <label>Winter_Watering_Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Twice per week</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every other week</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PlantTriggerTest.cls
@isTest
public with sharing class PlantTriggerTest {
    @isTest
    static void insertPlant_lastWateredSetup_nextWateringDateCalculatedCorrectly() {
        //GIVEN
        Species__c poto = new Species__c();
        poto.Winter_Watering_Frequency__c = 'Every other week';
        poto.Summer_Watering_Summer__c = 'Every other week';

        insert poto;

        Plant__c planta1 = new Plant__c();
        planta1.Last_Watered__c = System.today();
        planta1.Last_Fertilized__c = System.today();
        planta1.Species__c = poto.Id;
        //When
        Test.startTest();
        insert planta1;
        Test.stopTest();
        //Then
        planta1 = [SELECT Next_Water__c FROM Plant__c WHERE Id = :planta1.Id];
        System.assertEquals(System.today()+15,planta1.Next_Water__c);
    }


    @isTest
    static void updatePlant_lastWateredSetup_nextWateringDateCalculatedCorrectly() {
        //GIVEN
        Species__c poto = new Species__c();
        poto.Winter_Watering_Frequency__c = 'Every other week';
        poto.Summer_Watering_Summer__c = 'Every other week';

        insert poto;

        Plant__c planta1 = new Plant__c();
        planta1.Last_Watered__c = System.today() - 15;
        planta1.Last_Fertilized__c = System.today() - 15;
        planta1.Species__c = poto.Id;
        insert planta1;
        // then
        planta1 = [SELECT Next_Water__c FROM Plant__c WHERE Id = :planta1.Id];
        System.assertEquals(System.today(),planta1.Next_Water__c);

        planta1.Last_Watered__c = System.today();
        //When
        Test.startTest();
        update planta1;
        Test.stopTest();
        //Then
        planta1 = [SELECT Next_Water__c FROM Plant__c WHERE Id = :planta1.Id];
        System.assertEquals(System.today()+15,planta1.Next_Water__c);
    }
}